version: '3.9'

services:
  linode_s3_backup:
    restart: always
    image: tkgling/s4cmd-docker
    container_name: s4cmd_backup
    environment:
      SCHEDULE: $SCHEDULE 
      S3_REGION: $S3_REGION
      S3_BUCKET: $S3_BUCKET
      S3_ENDPOINT: $S3_ENDPOINT
      S3_ACCESS_KEY: $S3_ACCESS_KEY
      S3_SECRET_KEY: $S3_SECRET_KEY
    volumes:
      - ./output/txt2img:/output/txt2img
      - ./data:/data